/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
